In [51]:
import pandas as pd

In [52]:
df = pd.read_csv('../data/international_matches.csv')
df

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1993-08-08,Brazil,Mexico,South America,North America,8,14,0,0,1,...,No,Draw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1993-08-08,Guinea,Sierra Leone,Africa,Africa,65,86,0,0,1,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,No,Win,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN
23918,2022-06-14,Chile,Ghana,South America,Africa,28,60,1526,1387,0,...,Yes,Lose,79.0,74.0,75.5,76.7,78.2,75.5,76.0,78.2
23919,2022-06-14,Japan,Tunisia,Asia,Africa,23,35,1553,1499,0,...,No,Lose,73.0,NaN,75.2,75.0,77.5,70.8,72.3,74.0
23920,2022-06-14,Korea Republic,Egypt,Asia,Africa,29,32,1519,1500,4,...,No,Win,75.0,NaN,73.0,80.0,73.8,NaN,79.3,70.8

In [53]:
important_tournaments = ["FIFA World Cup","FIFA World Cup qualification","UEFA Euro",
 "UEFA Euro qualification","Copa América","Copa América qualification","AFC Asian Cup",
 "AFC Asian Cup qualification","African Cup of Nations","African Cup of Nations qualification",
 "Gold Cup", "Gold Cup qualification", "UEFA Nations League","CONCACAF Nations League","Confederations Cup"]

df = df[df['tournament'].isin(important_tournaments)]
df

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1993-08-08,Peru,Colombia,South America,South America,70,19,0,0,0,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1993-08-15,Australia,Canada,Oceania,North America,52,46,0,0,2,...,Yes,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23913,2022-06-14,Romania,Montenegro,Europe,Europe,48,70,1446,1342,0,...,No,Lose,77.0,65.0,73.5,73.7,75.0,76.2,74.7,68.2
23914,2022-06-14,Luxembourg,Faroe Islands,Europe,Europe,94,124,1229,1137,2,...,No,Draw,69.0,NaN,68.5,NaN,69.8,NaN,NaN,NaN
23915,2022-06-14,Turkey,Lithuania,Europe,Europe,43,138,1461,1092,2,...,No,Win,79.0,71.0,78.2,76.7,78.2,NaN,NaN,NaN
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,No,Win,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df = df[df['home_team_result'] != 'Draw']
df

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1993-08-08,Peru,Colombia,South America,South America,70,19,0,0,0,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1993-08-15,Australia,Canada,Oceania,North America,52,46,0,0,2,...,Yes,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23912,2022-06-14,Bosnia and Herzegovina,Finland,Europe,Europe,59,57,1388,1406,3,...,No,Win,76.0,83.0,74.2,77.0,78.0,70.0,72.3,73.5
23913,2022-06-14,Romania,Montenegro,Europe,Europe,48,70,1446,1342,0,...,No,Lose,77.0,65.0,73.5,73.7,75.0,76.2,74.7,68.2
23915,2022-06-14,Turkey,Lithuania,Europe,Europe,43,138,1461,1092,2,...,No,Win,79.0,71.0,78.2,76.7,78.2,NaN,NaN,NaN
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,No,Win,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df.isna().sum()

date                                0
home_team                           0
away_team                           0
home_team_continent                 0
away_team_continent                 0
home_team_fifa_rank                 0
away_team_fifa_rank                 0
home_team_total_fifa_points         0
away_team_total_fifa_points         0
home_team_score                     0
away_team_score                     0
tournament                          0
city                                0
country                             0
neutral_location                    0
shoot_out                           0
home_team_result                    0
home_team_goalkeeper_score       5570
away_team_goalkeeper_score       5743
home_team_mean_defense_score     5800
home_team_mean_offense_score     5484
home_team_mean_midfield_score    5619
away_team_mean_defense_score     5946
away_team_mean_offense_score     5668
away_team_mean_midfield_score    5796
dtype: int64

In [56]:
missing_values_columns = ['home_team_goalkeeper_score', 'away_team_goalkeeper_score', 'home_team_mean_defense_score', 'home_team_mean_offense_score',
'home_team_mean_midfield_score', 'away_team_mean_defense_score', 'away_team_mean_offense_score', 'away_team_mean_midfield_score']

for col in missing_values_columns:
    if 'home' in col:
        fn = df.groupby('home_team')[col].mean()
        df[col] = df[col].fillna(df['home_team'].map(fn))
    elif 'away' in col:
        fn = df.groupby('away_team')[col].mean()
        df[col] = df[col].fillna(df['away_team'].map(fn))
    df[col] = df[col].fillna(df[col].mean())
df.isna().sum()

date                             0
home_team                        0
away_team                        0
home_team_continent              0
away_team_continent              0
home_team_fifa_rank              0
away_team_fifa_rank              0
home_team_total_fifa_points      0
away_team_total_fifa_points      0
home_team_score                  0
away_team_score                  0
tournament                       0
city                             0
country                          0
neutral_location                 0
shoot_out                        0
home_team_result                 0
home_team_goalkeeper_score       0
away_team_goalkeeper_score       0
home_team_mean_defense_score     0
home_team_mean_offense_score     0
home_team_mean_midfield_score    0
away_team_mean_defense_score     0
away_team_mean_offense_score     0
away_team_mean_midfield_score    0
dtype: int64

In [57]:
df.sort_values('date')

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,No,Win,67.217391,79.820000,67.855000,68.633333,68.550000,79.660000,83.146000,78.752000
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,No,Win,71.516129,69.657895,70.648571,75.441935,75.116129,72.463636,75.800000,73.630556
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,No,Lose,74.425000,80.933333,74.957500,78.332500,74.395000,83.431111,88.268889,84.806667
5,1993-08-08,Peru,Colombia,South America,South America,70,19,0,0,0,...,No,Lose,69.696970,78.159091,72.419355,75.811429,74.058065,78.438636,80.845455,78.450000
10,1993-08-15,Australia,Canada,Oceania,North America,52,46,0,0,2,...,Yes,Win,78.350877,73.054054,72.354386,74.036842,74.047368,69.145946,71.486111,73.308108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23892,2022-06-14,Indonesia,Nepal,Asia,Asia,159,168,1001,978,7,...,No,Win,73.182905,72.422746,73.803216,74.491955,74.217284,73.226610,74.042989,73.736715
23891,2022-06-14,Kuwait,Jordan,Asia,Asia,146,91,1059,1259,0,...,No,Lose,73.182905,68.000000,73.803216,74.491955,74.217284,59.000000,74.042989,63.500000
23890,2022-06-14,Costa Rica,New Zealand,North America,Oceania,31,101,1503,1206,1,...,No,Win,88.000000,68.000000,71.500000,70.300000,69.200000,70.200000,70.700000,69.200000
23900,2022-06-14,Malaysia,Bangladesh,Asia,Asia,154,188,1035,903,4,...,No,Win,73.182905,72.422746,73.803216,74.491955,74.217284,73.226610,74.042989,73.736715
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,65.181818,65.000000,73.803216,74.491955,74.217284,64.000000,67.010000,73.736715

In [58]:
df['neutral_location'] = df['neutral_location'].astype(int)
df['match_results'] = (df['home_team_result'] == 'Win').astype(int)

In [59]:
df['recent_home_win_rate'] = df.groupby('home_team')['match_results'].transform(lambda x: x.shift(1).rolling(5, min_periods = 3).mean())
df['recent_away_win_rate'] = df.groupby('away_team')['match_results'].transform(lambda x: (x == 0).astype(int).shift(1).rolling(5, min_periods = 3).mean())
df

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score,match_results,recent_home_win_rate,recent_away_win_rate
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,79.820000,67.855000,68.633333,68.550000,79.660000,83.146000,78.752000,1,NaN,NaN
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,69.657895,70.648571,75.441935,75.116129,72.463636,75.800000,73.630556,1,NaN,NaN
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,80.933333,74.957500,78.332500,74.395000,83.431111,88.268889,84.806667,0,NaN,NaN
5,1993-08-08,Peru,Colombia,South America,South America,70,19,0,0,0,...,78.159091,72.419355,75.811429,74.058065,78.438636,80.845455,78.450000,0,NaN,NaN
10,1993-08-15,Australia,Canada,Oceania,North America,52,46,0,0,2,...,73.054054,72.354386,74.036842,74.047368,69.145946,71.486111,73.308108,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23912,2022-06-14,Bosnia and Herzegovina,Finland,Europe,Europe,59,57,1388,1406,3,...,83.000000,74.200000,77.000000,78.000000,70.000000,72.300000,73.500000,1,0.2,0.4
23913,2022-06-14,Romania,Montenegro,Europe,Europe,48,70,1446,1342,0,...,65.000000,73.500000,73.700000,75.000000,76.200000,74.700000,68.200000,0,0.8,0.4
23915,2022-06-14,Turkey,Lithuania,Europe,Europe,43,138,1461,1092,2,...,71.000000,78.200000,76.700000,78.200000,64.845833,65.850000,62.616667,1,0.8,0.0
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,72.422746,66.055556,62.925000,63.380000,73.226610,74.042989,73.736715,1,0.0,0.2
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,65.000000,73.803216,74.491955,74.217284,64.000000,67.010000,73.736715,0,0.0,0.6

In [60]:
df = df.dropna()
df

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score,match_results,recent_home_win_rate,recent_away_win_rate
435,1994-07-09,Italy,Spain,Europe,Europe,4,5,0,0,2,...,88.523077,85.146552,85.317241,84.175862,85.430769,85.655385,86.912308,1,0.750000,1.00
443,1994-07-16,Sweden,Bulgaria,Europe,Europe,10,29,0,0,4,...,73.290323,77.103390,81.410169,77.732203,69.364516,72.467742,73.183871,1,0.666667,0.75
444,1994-07-17,Brazil,Italy,South America,Europe,3,4,0,0,0,...,88.206897,85.905479,86.939726,85.554795,85.191379,85.362069,84.103448,1,1.000000,1.00
525,1994-10-08,Estonia,Italy,Europe,Europe,116,2,0,0,0,...,88.206897,66.604762,62.492857,63.500000,85.191379,85.362069,84.103448,0,0.000000,0.75
616,1994-11-16,Northern Ireland,Republic of Ireland,Europe,Europe,39,11,0,0,0,...,78.184211,73.015000,69.167500,72.620000,76.673684,75.531579,76.865789,0,0.666667,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23912,2022-06-14,Bosnia and Herzegovina,Finland,Europe,Europe,59,57,1388,1406,3,...,83.000000,74.200000,77.000000,78.000000,70.000000,72.300000,73.500000,1,0.200000,0.40
23913,2022-06-14,Romania,Montenegro,Europe,Europe,48,70,1446,1342,0,...,65.000000,73.500000,73.700000,75.000000,76.200000,74.700000,68.200000,0,0.800000,0.40
23915,2022-06-14,Turkey,Lithuania,Europe,Europe,43,138,1461,1092,2,...,71.000000,78.200000,76.700000,78.200000,64.845833,65.850000,62.616667,1,0.800000,0.00
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,72.422746,66.055556,62.925000,63.380000,73.226610,74.042989,73.736715,1,0.000000,0.20
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,65.000000,73.803216,74.491955,74.217284,64.000000,67.010000,73.736715,0,0.000000,0.60

In [65]:
model_df = df.drop(columns = ['date', 'home_team_continent', 'away_team_continent', 'home_team_score', 'away_team_score', 'tournament', 'city', 'country', 'shoot_out', 'home_team_result'])
model_df

,home_team,away_team,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,neutral_location,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score,match_results,recent_home_win_rate,recent_away_win_rate
435,Italy,Spain,4,5,0,0,1,88.137931,88.523077,85.146552,85.317241,84.175862,85.430769,85.655385,86.912308,1,0.750000,1.00
443,Sweden,Bulgaria,10,29,0,0,1,76.457627,73.290323,77.103390,81.410169,77.732203,69.364516,72.467742,73.183871,1,0.666667,0.75
444,Brazil,Italy,3,4,0,0,1,86.561644,88.206897,85.905479,86.939726,85.554795,85.191379,85.362069,84.103448,1,1.000000,1.00
525,Estonia,Italy,116,2,0,0,0,67.771429,88.206897,66.604762,62.492857,63.500000,85.191379,85.362069,84.103448,0,0.000000,0.75
616,Northern Ireland,Republic of Ireland,39,11,0,0,0,72.550000,78.184211,73.015000,69.167500,72.620000,76.673684,75.531579,76.865789,0,0.666667,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23912,Bosnia and Herzegovina,Finland,59,57,1388,1406,0,76.000000,83.000000,74.200000,77.000000,78.000000,70.000000,72.300000,73.500000,1,0.200000,0.40
23913,Romania,Montenegro,48,70,1446,1342,0,77.000000,65.000000,73.500000,73.700000,75.000000,76.200000,74.700000,68.200000,0,0.800000,0.40
23915,Turkey,Lithuania,43,138,1461,1092,0,79.000000,71.000000,78.200000,76.700000,78.200000,64.845833,65.850000,62.616667,1,0.800000,0.00
23916,Moldova,Andorra,180,153,932,1040,0,65.000000,72.422746,66.055556,62.925000,63.380000,73.226610,74.042989,73.736715,1,0.000000,0.20
23917,Liechtenstein,Latvia,192,135,895,1105,0,65.181818,65.000000,73.803216,74.491955,74.217284,64.000000,67.010000,73.736715,0,0.000000,0.60

In [66]:
model_df.to_csv('../data/preprocessed_international_matches.csv')

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [67]:
X = model_df.drop(columns = ['match_results', 'home_team', 'away_team'])
y = model_df['match_results']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [69]:
model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

/Users/mohith/Desktop/Worldcup Predictor/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [70]:
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.64      0.69       636
           1       0.80      0.87      0.84      1057

    accuracy                           0.78      1693
   macro avg       0.78      0.75      0.76      1693
weighted avg       0.78      0.78      0.78      1693

In [71]:
import pickle

In [73]:
pickle.dump(model, open('predict_model2.pkl', 'wb'))