In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("../data/results.csv")
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [52]:
df = df.dropna()

In [53]:
filtered_df = df[(df["tournament"] != "Friendly") & (df["away_score"] != df["home_score"])]
filtered_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
29,1884-01-26,Northern Ireland,Scotland,0.0,5.0,British Home Championship,Belfast,Ireland,False
30,1884-02-09,Wales,Northern Ireland,6.0,0.0,British Home Championship,Wrexham,Wales,False
31,1884-02-23,Northern Ireland,England,1.0,8.0,British Home Championship,Belfast,Ireland,False
32,1884-03-15,Scotland,England,1.0,0.0,British Home Championship,Glasgow,Scotland,False
33,1884-03-17,Wales,England,0.0,4.0,British Home Championship,Wrexham,Wales,False
...,...,...,...,...,...,...,...,...,...
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False
49212,2026-03-31,Cameroon,China PR,2.0,0.0,FIFA Series,Melbourne,Australia,True
49213,2026-03-31,Australia,Curaçao,5.0,1.0,FIFA Series,Melbourne,Australia,False
49214,2026-03-31,Kazakhstan,Comoros,1.0,0.0,FIFA Series,Astana,Kazakhstan,False

In [54]:
filtered_df['match_results'] = (filtered_df['home_score'] > filtered_df['away_score']).astype(int)
filtered_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,match_results
29,1884-01-26,Northern Ireland,Scotland,0.0,5.0,British Home Championship,Belfast,Ireland,False,0
30,1884-02-09,Wales,Northern Ireland,6.0,0.0,British Home Championship,Wrexham,Wales,False,1
31,1884-02-23,Northern Ireland,England,1.0,8.0,British Home Championship,Belfast,Ireland,False,0
32,1884-03-15,Scotland,England,1.0,0.0,British Home Championship,Glasgow,Scotland,False,1
33,1884-03-17,Wales,England,0.0,4.0,British Home Championship,Wrexham,Wales,False,0
...,...,...,...,...,...,...,...,...,...,...
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,1
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,0
49212,2026-03-31,Cameroon,China PR,2.0,0.0,FIFA Series,Melbourne,Australia,True,1
49213,2026-03-31,Australia,Curaçao,5.0,1.0,FIFA Series,Melbourne,Australia,False,1
49214,2026-03-31,Kazakhstan,Comoros,1.0,0.0,FIFA Series,Astana,Kazakhstan,False,1

In [55]:
filtered_df = filtered_df[filtered_df["date"] >= "2000-01-01"]
filtered_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,match_results
24079,2000-01-23,China PR,Philippines,8.0,0.0,AFC Asian Cup qualification,Hanoi,Vietnam,True,1
24080,2000-01-23,Egypt,Zambia,2.0,0.0,African Cup of Nations,Kano,Nigeria,True,1
24082,2000-01-23,Nigeria,Tunisia,4.0,2.0,African Cup of Nations,Lagos,Nigeria,False,1
24083,2000-01-23,South Africa,Gabon,3.0,1.0,African Cup of Nations,Kumasi,Ghana,True,1
24084,2000-01-23,Vietnam,Guam,11.0,0.0,AFC Asian Cup qualification,Hanoi,Vietnam,False,1
...,...,...,...,...,...,...,...,...,...,...
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,1
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,0
49212,2026-03-31,Cameroon,China PR,2.0,0.0,FIFA Series,Melbourne,Australia,True,1
49213,2026-03-31,Australia,Curaçao,5.0,1.0,FIFA Series,Melbourne,Australia,False,1
49214,2026-03-31,Kazakhstan,Comoros,1.0,0.0,FIFA Series,Astana,Kazakhstan,False,1

In [56]:

important_tournaments = [
    "FIFA World Cup",
    "FIFA World Cup qualification",
    "UEFA Euro",
    "UEFA Euro qualification",
    "Copa América",
    "African Cup of Nations",
    "African Cup of Nations qualification",
    "AFC Asian Cup",
    "AFC Asian Cup qualification",
    "Gold Cup",
]
filtered_df = filtered_df[filtered_df["tournament"].isin(important_tournaments)]
filtered_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,match_results
24079,2000-01-23,China PR,Philippines,8.0,0.0,AFC Asian Cup qualification,Hanoi,Vietnam,True,1
24080,2000-01-23,Egypt,Zambia,2.0,0.0,African Cup of Nations,Kano,Nigeria,True,1
24082,2000-01-23,Nigeria,Tunisia,4.0,2.0,African Cup of Nations,Lagos,Nigeria,False,1
24083,2000-01-23,South Africa,Gabon,3.0,1.0,African Cup of Nations,Kumasi,Ghana,True,1
24084,2000-01-23,Vietnam,Guam,11.0,0.0,AFC Asian Cup qualification,Hanoi,Vietnam,False,1
...,...,...,...,...,...,...,...,...,...,...
49093,2026-03-26,Denmark,North Macedonia,4.0,0.0,FIFA World Cup qualification,Copenhagen,Denmark,False,1
49206,2026-03-31,DR Congo,Jamaica,1.0,0.0,FIFA World Cup qualification,Zapopan,Mexico,True,1
49207,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,True,1
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,1
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,0

In [57]:
filtered_df["neutral"] = filtered_df["neutral"].astype(int)
filtered_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,match_results
24079,2000-01-23,China PR,Philippines,8.0,0.0,AFC Asian Cup qualification,Hanoi,Vietnam,1,1
24080,2000-01-23,Egypt,Zambia,2.0,0.0,African Cup of Nations,Kano,Nigeria,1,1
24082,2000-01-23,Nigeria,Tunisia,4.0,2.0,African Cup of Nations,Lagos,Nigeria,0,1
24083,2000-01-23,South Africa,Gabon,3.0,1.0,African Cup of Nations,Kumasi,Ghana,1,1
24084,2000-01-23,Vietnam,Guam,11.0,0.0,AFC Asian Cup qualification,Hanoi,Vietnam,0,1
...,...,...,...,...,...,...,...,...,...,...
49093,2026-03-26,Denmark,North Macedonia,4.0,0.0,FIFA World Cup qualification,Copenhagen,Denmark,0,1
49206,2026-03-31,DR Congo,Jamaica,1.0,0.0,FIFA World Cup qualification,Zapopan,Mexico,1,1
49207,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,1,1
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,0,1
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,0,0

In [58]:
filtered_df = filtered_df.sort_values("date")

filtered_df["home_recent_wins"] = (filtered_df.groupby("home_team")["match_results"].transform(lambda x: x.shift(1).rolling(5).sum()))
filtered_df["away_recent_wins"] = (filtered_df.groupby("away_team")["match_results"].transform(lambda x: (x == 0).astype(int).shift(1).rolling(5).sum()))
filtered_df["home_recent_goals_scored"] = (filtered_df.groupby("home_team")["home_score"].transform(lambda x: x.shift(1).rolling(5).sum()))
filtered_df["away_recent_goals_scored"] = (filtered_df.groupby("away_team")["away_score"].transform(lambda x: x.shift(1).rolling(5).sum()))
filtered_df["home_recent_goals_conceded"] = (filtered_df.groupby("home_team")["away_score"].transform(lambda x: x.shift(1).rolling(5).sum()))
filtered_df["away_recent_goals_conceded"] = (filtered_df.groupby("away_team")["home_score"].transform(lambda x: x.shift(1).rolling(5).sum()))
filtered_df["home_win_rate"] = (filtered_df.groupby("home_team")["match_results"].transform(lambda x: x.shift(1).expanding(min_periods = 5).mean()))
filtered_df["away_win_rate"] = (filtered_df.groupby("away_team")["match_results"].transform(lambda x: (x==0).astype(int).shift(1).expanding(min_periods = 5).mean()))
filtered_df["goal_difference"] = filtered_df["home_score"] - filtered_df["away_score"]
filtered_df["home_average_goal_difference"] = (filtered_df.groupby("home_team")["goal_difference"].transform(lambda x: x.shift(1).expanding(min_periods = 5).mean()))
filtered_df["away_average_goal_difference"] = (filtered_df.groupby("away_team")["goal_difference"].transform(lambda x: x.shift(1).expanding(min_periods = 5).mean()*-1))

In [59]:
model_df = filtered_df.dropna().drop(columns=["home_score", "away_score", "city", "country", "date", "tournament", "goal_difference" ])
model_df

,home_team,away_team,neutral,match_results,home_recent_wins,away_recent_wins,home_recent_goals_scored,away_recent_goals_scored,home_recent_goals_conceded,away_recent_goals_conceded,home_win_rate,away_win_rate,home_average_goal_difference,away_average_goal_difference
25037,Saint Vincent and the Grenadines,Honduras,0,0,3.0,3.0,15.0,10.0,3.0,7.0,0.600000,0.666667,2.400000,0.833333
25061,Trinidad and Tobago,Panama,0,1,5.0,1.0,17.0,4.0,1.0,17.0,0.875000,0.200000,2.750000,-2.600000
25117,Nigeria,Zambia,0,1,5.0,2.0,14.0,4.0,1.0,6.0,1.000000,0.400000,2.428571,-0.400000
25233,Cameroon,Zambia,0,1,5.0,2.0,14.0,4.0,1.0,5.0,0.857143,0.333333,2.142857,-0.500000
25347,Costa Rica,Trinidad and Tobago,0,1,4.0,3.0,13.0,5.0,6.0,9.0,0.800000,0.500000,1.400000,-1.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49088,Poland,Albania,0,1,3.0,3.0,8.0,6.0,6.0,5.0,0.728814,0.326923,1.559322,-0.730769
49207,Iraq,Bolivia,1,1,4.0,0.0,5.0,1.0,3.0,18.0,0.716667,0.028986,1.266667,-2.478261
49209,Sweden,Poland,0,1,2.0,3.0,8.0,8.0,6.0,6.0,0.764706,0.578947,1.573529,0.473684
49206,DR Congo,Jamaica,1,1,3.0,3.0,6.0,7.0,5.0,6.0,0.758065,0.344828,1.177419,-0.689655
49210,Kosovo,Turkey,0,0,2.0,4.0,4.0,14.0,5.0,7.0,0.285714,0.641791,-1.285714,0.507463

In [60]:
model_df.to_csv('../data/preprocessed_results.csv')

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [62]:
X = model_df.drop(columns = ["match_results", "home_team", "away_team"])
y = model_df["match_results"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [63]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [64]:
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.752501667778519
              precision    recall  f1-score   support

           0       0.71      0.58      0.64       564
           1       0.77      0.86      0.81       935

    accuracy                           0.75      1499
   macro avg       0.74      0.72      0.72      1499
weighted avg       0.75      0.75      0.75      1499

In [65]:
import pickle

In [66]:
pickle.dump(model, open('predict_model.pkl', 'wb'))